version: '2'
services:
  web:
    build: ./
    ports:
      - 5000
    networks:
      - front-tier
      - back-tier

  redis:
    image: redis
    networks:
      - back-tier

  lb:
    image: dockercloud/haproxy
    ports:
      - 80:80
    links:
      - web
    networks:
      - front-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
